"""agregar external_ref a pedido

Revision ID: 6857510f557d
Revises: 7beebc130eb3
Create Date: 2026-06-19 02:33:06.192930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6857510f557d'
down_revision = '7beebc130eb3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pedido', sa.Column('external_ref', sa.Uuid(), nullable=False))
    op.create_index(op.f('ix_pedido_external_ref'), 'pedido', ['external_ref'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pedido_external_ref'), table_name='pedido')
    op.drop_column('pedido', 'external_ref')
    # ### end Alembic commands ###
