"""add pagos

Revision ID: 7beebc130eb3
Revises: 6631f3fba2d6
Create Date: 2026-06-18 12:17:17.162758

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision = '7beebc130eb3'
down_revision = '6631f3fba2d6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pago',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('mp_payment_id', sa.Integer(), nullable=True),
    sa.Column('mp_status', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('mp_status_detail', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('external_reference', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('idempotency_key', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedido.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_pago_external_reference'), 'pago', ['external_reference'], unique=False)
    op.create_index(op.f('ix_pago_mp_payment_id'), 'pago', ['mp_payment_id'], unique=True)
    op.create_index(op.f('ix_pago_pedido_id'), 'pago', ['pedido_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pago_pedido_id'), table_name='pago')
    op.drop_index(op.f('ix_pago_mp_payment_id'), table_name='pago')
    op.drop_index(op.f('ix_pago_external_reference'), table_name='pago')
    op.drop_table('pago')
    # ### end Alembic commands ###
